services:
  server:
    container_name: planet-window-server
    image: ghcr.io/coccoto/planet-window-server:latest
    restart: unless-stopped
    ports:
      - "18040:18040"
    env_file:
      - ./server/.env
    networks:
      - planet-window-network

  client:
    container_name: planet-window-client
    image: ghcr.io/coccoto/planet-window-client:latest
    restart: unless-stopped
    ports:
      - "18030:18030"
    env_file:
      - ./client/.env
    networks:
      - planet-window-network
    depends_on:
      - server

networks:
  planet-window-network:
    name: planet-window-network
    external: true
